# Generated by Django 4.2.3 on 2023-07-20 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_year_of_admission_student_date_of_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='service.studygroup', verbose_name='Группа'),
        ),
    ]
