# Generated by Django 4.2.3 on 2023-07-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionOfTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название направления')),
                ('direction_code', models.IntegerField(default=1, verbose_name='КОд дисциплины')),
            ],
            options={
                'verbose_name': 'Направленние подготовки',
                'verbose_name_plural': 'Направления подготовки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название дисциплины')),
                ('direction', models.ManyToManyField(to='admin_service.directionoftraining', verbose_name='Направление подготовки')),
            ],
            options={
                'verbose_name': 'Учебная дисциплина',
                'verbose_name_plural': 'Учебные дисциплины',
                'ordering': ['-name'],
            },
        ),
    ]
