# Generated by Django 4.2.3 on 2023-07-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('admin_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionoftraining',
            name='curator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.curator', verbose_name='Куратор'),
        ),
    ]
